INSERT INTO PRODUCT_CATEGORY (CATEGORY_NAME, CATEGORY_DESCRIPTION ) 
VALUES('CATEGORY ROOT', 'DESCRIPTION ROOT');

INSERT INTO PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_CATEGORY_ID, PRODUCT_COMPANY_ID, PRODUCT_DESCRIPTION) 
VALUES('0123456789ABCDEF', 'NAME ONE', 5, 1, 'DESCRIPTION ONE');
